### PR TITLE
Create transparent navbar

### PR DESCRIPTION
**Pull request by Gregkur**
Added the navbar to app.html.erb
If/else statement on the top/right, changes into user name if lf logged in, if not, it's a pth to login/register

### CODE REVIEW

**Comment by Gregkur** [comment]
@Piavh @LorenzCronenberg @melwers

**Comment by ghost** [comment]
One question:
If you are not logged in (like it seems in the picture), shouldn't the drop down be 'sign in' (instead of 'sign out')?
Other than that, looks good :)

**Comment by Gregkur** [comment]
> One question:
> If you are not logged in (like it seems in the picture), shouldn't the drop down be 'sign in' (instead of 'sign out')?
> Other than that, looks good :)
@melwers
True that, I'll make that If/else also :)

**Comment by Gregkur** [comment]
@melwers @Piavh @LorenzCronenberg 
Added if/else now, also changed a form a bit 
we're cool with merging that?

**Comment by ghost** [comment]
Looks good to me!
Should I do it then?

**Comment by Gregkur** [comment]
Yeah, would rather work on this with the dashboard

**Comment by Gregkur** [comment]
> Looks good to me!
> Should I do it then?

Can you do it? Or I need to?  @melwers

**Pull request merged**
